/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RedmineGanttPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  baseUrl: "",
  apiKey: "",
  projectId: "",
  includeClosed: false,
  defaultScale: "week"
};
var RedmineGanttSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Redmine URL").setDesc("\u4F8B: https://redmine.example.local").addText(
      (text) => text.setPlaceholder("https://redmine.example.local").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API\u30AD\u30FC").setDesc(
      "Redmine\u306E\u300C\u500B\u4EBA\u8A2D\u5B9A\u300D\u30DA\u30FC\u30B8\u3067\u78BA\u8A8D\u3067\u304D\u308BAPI\u30A2\u30AF\u30BB\u30B9\u30AD\u30FC\u3002\u6CE8\u610F: \u30AD\u30FC\u306FVault\u5185\u306E data.json \u306B\u5E73\u6587\u3067\u4FDD\u5B58\u3055\u308C\u307E\u3059\u3002Vault\u3092\u540C\u671F\u3057\u3066\u3044\u308B\u5834\u5408\u306F\u30AD\u30FC\u3082\u540C\u671F\u3055\u308C\u307E\u3059\u3002"
    ).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("API access key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8").setDesc(
      "\u8868\u793A\u3059\u308B\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u306E\u8B58\u5225\u5B50\u307E\u305F\u306FID(\u4F8B: my-project)\u3002\u7A7A\u306E\u5834\u5408\u306F\u95B2\u89A7\u53EF\u80FD\u306A\u5168\u30C1\u30B1\u30C3\u30C8\u3092\u53D6\u5F97\u3057\u307E\u3059\u3002"
    ).addText(
      (text) => text.setPlaceholder("project-identifier").setValue(this.plugin.settings.projectId).onChange(async (value) => {
        this.plugin.settings.projectId = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5B8C\u4E86\u30C1\u30B1\u30C3\u30C8\u3092\u542B\u3081\u308B").setDesc("\u30AA\u30F3\u306B\u3059\u308B\u3068\u7D42\u4E86\u30B9\u30C6\u30FC\u30BF\u30B9\u306E\u30C1\u30B1\u30C3\u30C8\u3082\u8868\u793A\u3057\u307E\u3059\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeClosed).onChange(async (value) => {
        this.plugin.settings.includeClosed = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u65E2\u5B9A\u306E\u30B9\u30B1\u30FC\u30EB").setDesc("\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u3092\u958B\u3044\u305F\u3068\u304D\u306E\u6642\u9593\u8EF8\u30B9\u30B1\u30FC\u30EB\u3002").addDropdown(
      (dropdown) => dropdown.addOption("day", "\u65E5").addOption("week", "\u9031").addOption("month", "\u6708").setValue(this.plugin.settings.defaultScale).onChange(async (value) => {
        this.plugin.settings.defaultScale = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/gantt/GanttView.ts
var import_obsidian3 = require("obsidian");

// src/redmine/client.ts
var import_obsidian2 = require("obsidian");
var PAGE_SIZE = 100;
var MAX_ISSUES = 1e4;
var RedmineApiError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
var RedmineClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  get baseUrl() {
    return this.settings.baseUrl.replace(/\/+$/, "");
  }
  issueUrl(issueId) {
    return `${this.baseUrl}/issues/${issueId}`;
  }
  async request(method, path, params) {
    if (!this.baseUrl) {
      throw new RedmineApiError(0, "Redmine URL\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    if (!this.settings.apiKey) {
      throw new RedmineApiError(0, "API\u30AD\u30FC\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    const qs = params ? new URLSearchParams(params).toString() : "";
    const url = `${this.baseUrl}${path}${qs ? "?" + qs : ""}`;
    let response;
    try {
      response = await (0, import_obsidian2.requestUrl)({
        url,
        method,
        headers: {
          "X-Redmine-API-Key": this.settings.apiKey,
          Accept: "application/json"
        },
        throw: false
      });
    } catch (e) {
      throw new RedmineApiError(
        0,
        `Redmine\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093: ${url}
URL\u306E\u8AA4\u308A\u3001\u30CD\u30C3\u30C8\u30EF\u30FC\u30AF\u672A\u5230\u9054\u3001\u307E\u305F\u306F\u81EA\u5DF1\u7F72\u540D\u8A3C\u660E\u66F8\u304C\u539F\u56E0\u306E\u53EF\u80FD\u6027\u304C\u3042\u308A\u307E\u3059\u3002(${String(e)})`
      );
    }
    if (response.status === 401) {
      throw new RedmineApiError(401, "\u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002API\u30AD\u30FC\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    if (response.status === 403) {
      throw new RedmineApiError(
        403,
        "\u30A2\u30AF\u30BB\u30B9\u304C\u62D2\u5426\u3055\u308C\u307E\u3057\u305F\u3002REST API\u304C\u6709\u52B9\u304B(\u7BA1\u7406\u2192\u8A2D\u5B9A\u2192API)\u3001\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u306E\u95B2\u89A7\u6A29\u9650\u304C\u3042\u308B\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
      );
    }
    if (response.status === 404) {
      throw new RedmineApiError(404, `\u898B\u3064\u304B\u308A\u307E\u305B\u3093: ${path}(\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u8B58\u5225\u5B50\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044)`);
    }
    if (response.status >= 400) {
      throw new RedmineApiError(response.status, `Redmine API\u30A8\u30E9\u30FC (HTTP ${response.status}): ${path}`);
    }
    return response.json;
  }
  /** 設定に基づき、対象チケットをページングしながら全件取得する */
  async fetchIssues() {
    const issues = [];
    let offset = 0;
    for (; ; ) {
      const params = {
        limit: String(PAGE_SIZE),
        offset: String(offset),
        status_id: this.settings.includeClosed ? "*" : "open",
        sort: "start_date:asc,id:asc"
      };
      if (this.settings.projectId) {
        params.project_id = this.settings.projectId;
        params.subproject_id = "*";
      }
      const res = await this.request("GET", "/issues.json", params);
      issues.push(...res.issues);
      offset += res.issues.length;
      if (res.issues.length === 0 || offset >= res.total_count || offset >= MAX_ISSUES) {
        break;
      }
    }
    return issues;
  }
  /** 接続テスト等に使うプロジェクト一覧取得 */
  async fetchProjects() {
    const res = await this.request("GET", "/projects.json", {
      limit: String(PAGE_SIZE)
    });
    return res.projects;
  }
};

// src/redmine/mapper.ts
function parseDate(s) {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}
function toTask(issue) {
  var _a, _b, _c, _d, _e;
  let start = null;
  let due = null;
  let startIsFallback = false;
  let dueIsFallback = false;
  if (issue.start_date) {
    start = parseDate(issue.start_date);
  }
  if (issue.due_date) {
    due = parseDate(issue.due_date);
  }
  if (!start && due) {
    const created = new Date(issue.created_on);
    start = new Date(created.getFullYear(), created.getMonth(), created.getDate());
    if (start > due)
      start = due;
    startIsFallback = true;
  }
  if (start && !due) {
    due = start;
    dueIsFallback = true;
  }
  return {
    id: issue.id,
    subject: issue.subject,
    start,
    due,
    doneRatio: (_a = issue.done_ratio) != null ? _a : 0,
    assignee: (_c = (_b = issue.assigned_to) == null ? void 0 : _b.name) != null ? _c : "",
    status: issue.status.name,
    tracker: issue.tracker.name,
    project: issue.project.name,
    parentId: (_e = (_d = issue.parent) == null ? void 0 : _d.id) != null ? _e : null,
    depth: 0,
    startIsFallback,
    dueIsFallback,
    isClosed: !!issue.closed_on
  };
}
function buildGanttModel(issues) {
  var _a;
  const all = issues.map(toTask);
  const dated = all.filter((t) => t.start !== null);
  const undated = all.filter((t) => t.start === null);
  const byId = new Map(dated.map((t) => [t.id, t]));
  const children = /* @__PURE__ */ new Map();
  const roots = [];
  for (const task of dated) {
    if (task.parentId !== null && byId.has(task.parentId)) {
      const list = (_a = children.get(task.parentId)) != null ? _a : [];
      list.push(task);
      children.set(task.parentId, list);
    } else {
      roots.push(task);
    }
  }
  const ordered = [];
  const visit = (task, depth) => {
    var _a2;
    task.depth = depth;
    ordered.push(task);
    for (const child of (_a2 = children.get(task.id)) != null ? _a2 : []) {
      visit(child, depth + 1);
    }
  };
  for (const root of roots)
    visit(root, 0);
  return { tasks: ordered, undated };
}

// src/gantt/scale.ts
var MS_PER_DAY = 24 * 60 * 60 * 1e3;
var PX_PER_DAY = {
  day: 32,
  week: 12,
  month: 4
};
function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function addDays(d, days) {
  const r = new Date(d);
  r.setDate(r.getDate() + days);
  return r;
}
function diffDays(from, to) {
  return Math.round((startOfDay(to).getTime() - startOfDay(from).getTime()) / MS_PER_DAY);
}
function computeRange(tasks) {
  const today = startOfDay(/* @__PURE__ */ new Date());
  let min = today;
  let max = today;
  for (const t of tasks) {
    if (t.start && t.start < min)
      min = startOfDay(t.start);
    if (t.due && t.due > max)
      max = startOfDay(t.due);
  }
  const start = addDays(min, -7);
  const end = addDays(max, 14);
  return { start, end, days: diffDays(start, end) + 1 };
}
function computeTicks(range, scale) {
  const ppd = PX_PER_DAY[scale];
  const major = [];
  const minor = [];
  const gridX = [];
  for (let i = 0; i <= range.days; i++) {
    const d = addDays(range.start, i);
    const x = i * ppd;
    if (d.getDate() === 1 || i === 0) {
      major.push({ x, label: `${d.getFullYear()}/${d.getMonth() + 1}` });
      if (scale === "month")
        gridX.push(x);
    }
    if (scale === "day") {
      minor.push({ x, label: String(d.getDate()) });
      gridX.push(x);
    } else if (scale === "week" && d.getDay() === 1) {
      minor.push({ x, label: `${d.getMonth() + 1}/${d.getDate()}` });
      gridX.push(x);
    }
  }
  return { major, minor, gridX };
}
function weekendBands(range, scale) {
  if (scale !== "day")
    return [];
  const ppd = PX_PER_DAY[scale];
  const bands = [];
  for (let i = 0; i <= range.days; i++) {
    const d = addDays(range.start, i);
    const day = d.getDay();
    if (day === 0 || day === 6) {
      bands.push({ x: i * ppd, w: ppd });
    }
  }
  return bands;
}

// src/gantt/renderer.ts
var ROW_HEIGHT = 30;
var HEADER_HEIGHT = 40;
var BAR_PADDING = 7;
var LEFT_WIDTH = 320;
var INDENT = 16;
var SVG_NS = "http://www.w3.org/2000/svg";
function svg(tag, attrs = {}) {
  const el = document.createElementNS(SVG_NS, tag);
  for (const [k, v] of Object.entries(attrs)) {
    el.setAttribute(k, String(v));
  }
  return el;
}
function renderGantt(container, model, scale, opts) {
  container.empty();
  if (model.tasks.length === 0 && model.undated.length === 0) {
    container.createDiv({ cls: "rg-empty", text: "\u8868\u793A\u3067\u304D\u308B\u30C1\u30B1\u30C3\u30C8\u304C\u3042\u308A\u307E\u305B\u3093\u3002" });
    return;
  }
  const range = computeRange(model.tasks);
  const ppd = PX_PER_DAY[scale];
  const chartWidth = (range.days + 1) * ppd;
  const chartHeight = HEADER_HEIGHT + model.tasks.length * ROW_HEIGHT;
  const body = container.createDiv({ cls: "rg-body" });
  const left = body.createDiv({ cls: "rg-left" });
  left.style.width = `${LEFT_WIDTH}px`;
  const leftHeader = left.createDiv({ cls: "rg-left-header" });
  leftHeader.style.height = `${HEADER_HEIGHT}px`;
  leftHeader.setText("\u30C1\u30B1\u30C3\u30C8");
  for (const task of model.tasks) {
    const row = left.createDiv({ cls: "rg-left-row" });
    row.style.height = `${ROW_HEIGHT}px`;
    row.style.paddingLeft = `${8 + task.depth * INDENT}px`;
    const link = row.createEl("a", {
      cls: "rg-issue-link",
      text: `#${task.id} ${task.subject}`,
      href: opts.issueUrl(task.id)
    });
    link.setAttr("title", taskTooltip(task));
    if (task.isClosed)
      row.addClass("rg-row-closed");
    if (task.assignee) {
      row.createSpan({ cls: "rg-assignee", text: task.assignee });
    }
  }
  const chart = body.createDiv({ cls: "rg-chart" });
  const root = svg("svg", {
    width: chartWidth,
    height: chartHeight,
    viewBox: `0 0 ${chartWidth} ${chartHeight}`
  });
  chart.appendChild(root);
  for (const band of weekendBands(range, scale)) {
    root.appendChild(
      svg("rect", {
        x: band.x,
        y: HEADER_HEIGHT,
        width: band.w,
        height: chartHeight - HEADER_HEIGHT,
        class: "rg-weekend"
      })
    );
  }
  const ticks = computeTicks(range, scale);
  for (const x of ticks.gridX) {
    root.appendChild(
      svg("line", { x1: x, y1: HEADER_HEIGHT, x2: x, y2: chartHeight, class: "rg-grid" })
    );
  }
  for (let i = 0; i <= model.tasks.length; i++) {
    const y = HEADER_HEIGHT + i * ROW_HEIGHT;
    root.appendChild(svg("line", { x1: 0, y1: y, x2: chartWidth, y2: y, class: "rg-grid" }));
  }
  for (const tick of ticks.major) {
    const t = svg("text", { x: tick.x + 4, y: 15, class: "rg-tick-major" });
    t.textContent = tick.label;
    root.appendChild(t);
    root.appendChild(
      svg("line", { x1: tick.x, y1: 0, x2: tick.x, y2: HEADER_HEIGHT, class: "rg-grid" })
    );
  }
  for (const tick of ticks.minor) {
    const t = svg("text", { x: tick.x + 3, y: 33, class: "rg-tick-minor" });
    t.textContent = tick.label;
    root.appendChild(t);
  }
  model.tasks.forEach((task, i) => {
    if (!task.start || !task.due)
      return;
    const x = diffDays(range.start, task.start) * ppd;
    const w = Math.max((diffDays(task.start, task.due) + 1) * ppd, 4);
    const y = HEADER_HEIGHT + i * ROW_HEIGHT + BAR_PADDING;
    const h = ROW_HEIGHT - BAR_PADDING * 2;
    const group = svg("g", { class: "rg-bar-group" });
    const barClass = "rg-bar" + (task.isClosed ? " rg-bar-closed" : "") + (task.startIsFallback || task.dueIsFallback ? " rg-bar-fallback" : "");
    const bar = svg("rect", { x, y, width: w, height: h, rx: 3, class: barClass });
    const title = svg("title");
    title.textContent = taskTooltip(task);
    bar.appendChild(title);
    group.appendChild(bar);
    if (task.doneRatio > 0) {
      group.appendChild(
        svg("rect", {
          x,
          y,
          width: w * Math.min(task.doneRatio, 100) / 100,
          height: h,
          rx: 3,
          class: "rg-bar-progress" + (task.isClosed ? " rg-bar-closed" : "")
        })
      );
    }
    group.addEventListener("click", () => {
      window.open(opts.issueUrl(task.id));
    });
    root.appendChild(group);
  });
  const todayX = diffDays(range.start, /* @__PURE__ */ new Date()) * ppd + ppd / 2;
  root.appendChild(
    svg("line", { x1: todayX, y1: 0, x2: todayX, y2: chartHeight, class: "rg-today" })
  );
  if (model.undated.length > 0) {
    const undated = container.createDiv({ cls: "rg-undated" });
    undated.createDiv({
      cls: "rg-undated-header",
      text: `\u65E5\u4ED8\u672A\u8A2D\u5B9A\u306E\u30C1\u30B1\u30C3\u30C8 (${model.undated.length}\u4EF6)`
    });
    for (const task of model.undated) {
      const row = undated.createDiv({ cls: "rg-undated-row" });
      row.createEl("a", {
        cls: "rg-issue-link",
        text: `#${task.id} ${task.subject}`,
        href: opts.issueUrl(task.id)
      });
      if (task.assignee)
        row.createSpan({ cls: "rg-assignee", text: task.assignee });
    }
  }
}
function taskTooltip(task) {
  const fmt = (d) => d ? `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}` : "-";
  const lines = [
    `#${task.id} ${task.subject}`,
    `${task.tracker} / ${task.status}`,
    `\u671F\u9593: ${fmt(task.start)}${task.startIsFallback ? "(\u63A8\u5B9A)" : ""} \u301C ${fmt(task.due)}${task.dueIsFallback ? "(\u672A\u8A2D\u5B9A)" : ""}`,
    `\u9032\u6357: ${task.doneRatio}%`
  ];
  if (task.assignee)
    lines.push(`\u62C5\u5F53: ${task.assignee}`);
  return lines.join("\n");
}

// src/gantt/GanttView.ts
var VIEW_TYPE_REDMINE_GANTT = "redmine-gantt-view";
var GanttView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.model = null;
    this.statusEl = null;
    this.chartEl = null;
    this.loading = false;
    this.plugin = plugin;
    this.scale = plugin.settings.defaultScale;
  }
  getViewType() {
    return VIEW_TYPE_REDMINE_GANTT;
  }
  getDisplayText() {
    return "Redmine Gantt";
  }
  getIcon() {
    return "gantt-chart";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("rg-view");
    const toolbar = container.createDiv({ cls: "rg-toolbar" });
    const refreshBtn = toolbar.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian3.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.setAttr("aria-label", "\u518D\u53D6\u5F97");
    refreshBtn.addEventListener("click", () => void this.refresh());
    const scaleSelect = toolbar.createEl("select", { cls: "dropdown rg-scale-select" });
    for (const [value, label] of [
      ["day", "\u65E5"],
      ["week", "\u9031"],
      ["month", "\u6708"]
    ]) {
      const option = scaleSelect.createEl("option", { text: label });
      option.value = value;
    }
    scaleSelect.value = this.scale;
    scaleSelect.addEventListener("change", () => {
      this.scale = scaleSelect.value;
      this.renderChart();
    });
    this.statusEl = toolbar.createDiv({ cls: "rg-status" });
    this.chartEl = container.createDiv({ cls: "rg-chart-container" });
    await this.refresh();
  }
  async refresh() {
    if (this.loading || !this.chartEl)
      return;
    this.loading = true;
    this.setStatus("\u53D6\u5F97\u4E2D\u2026");
    try {
      const client = new RedmineClient(this.plugin.settings);
      const issues = await client.fetchIssues();
      this.model = buildGanttModel(issues);
      this.renderChart();
      const now = /* @__PURE__ */ new Date();
      const hh = String(now.getHours()).padStart(2, "0");
      const mm = String(now.getMinutes()).padStart(2, "0");
      this.setStatus(`${issues.length}\u4EF6 / \u6700\u7D42\u66F4\u65B0 ${hh}:${mm}`);
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      this.setStatus("\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
      this.chartEl.empty();
      this.chartEl.createDiv({ cls: "rg-error", text: message });
      new import_obsidian3.Notice(`Redmine Gantt: ${message}`);
    } finally {
      this.loading = false;
    }
  }
  renderChart() {
    if (!this.chartEl || !this.model)
      return;
    const client = new RedmineClient(this.plugin.settings);
    renderGantt(this.chartEl, this.model, this.scale, {
      issueUrl: (id) => client.issueUrl(id)
    });
  }
  setStatus(text) {
    var _a;
    (_a = this.statusEl) == null ? void 0 : _a.setText(text);
  }
  async onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var RedmineGanttPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_REDMINE_GANTT, (leaf) => new GanttView(leaf, this));
    this.addRibbonIcon("gantt-chart", "Redmine Gantt \u3092\u958B\u304F", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-gantt-view",
      name: "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u3092\u958B\u304F",
      callback: () => void this.activateView()
    });
    this.addSettingTab(new RedmineGanttSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_REDMINE_GANTT);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_REDMINE_GANTT, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
