/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RedmineGanttPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var PLAN_STATUS_LABELS = {
  todo: "\u672A\u7740\u624B",
  doing: "\u9032\u884C\u4E2D",
  done: "\u5B8C\u4E86"
};
var DEFAULT_SETTINGS = {
  baseUrl: "",
  apiKey: "",
  defaultScale: "week",
  filters: [],
  activeFilter: "",
  viewMode: "gantt",
  planItems: [],
  assigneeColors: [],
  tableFontSize: 11
};
var RedmineGanttSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Redmine URL").setDesc("\u4F8B: https://redmine.example.local").addText(
      (text) => text.setPlaceholder("https://redmine.example.local").setValue(this.plugin.settings.baseUrl).onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API\u30AD\u30FC").setDesc(
      "Redmine\u306E\u300C\u500B\u4EBA\u8A2D\u5B9A\u300D\u30DA\u30FC\u30B8\u3067\u78BA\u8A8D\u3067\u304D\u308BAPI\u30A2\u30AF\u30BB\u30B9\u30AD\u30FC\u3002\u6CE8\u610F: \u30AD\u30FC\u306FVault\u5185\u306E data.json \u306B\u5E73\u6587\u3067\u4FDD\u5B58\u3055\u308C\u307E\u3059\u3002Vault\u3092\u540C\u671F\u3057\u3066\u3044\u308B\u5834\u5408\u306F\u30AD\u30FC\u3082\u540C\u671F\u3055\u308C\u307E\u3059\u3002"
    ).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("API access key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u65E2\u5B9A\u306E\u30B9\u30B1\u30FC\u30EB").setDesc("\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u3092\u958B\u3044\u305F\u3068\u304D\u306E\u6642\u9593\u8EF8\u30B9\u30B1\u30FC\u30EB\u3002").addDropdown(
      (dropdown) => dropdown.addOption("day", "\u65E5").addOption("week", "\u9031").addOption("month", "\u6708").setValue(this.plugin.settings.defaultScale).onChange(async (value) => {
        this.plugin.settings.defaultScale = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u5B57\u30B5\u30A4\u30BA").setDesc("\u30C6\u30FC\u30D6\u30EB\u3068\u30AC\u30F3\u30C8\u306E\u4E00\u89A7\u90E8\u5206\u306B\u9069\u7528(px\u5358\u4F4D)\u3002\u884C\u306E\u9AD8\u3055\u30FB\u30D0\u30C3\u30B8\u985E\u3082\u9023\u52D5\u3057\u3066\u7E2E\u5C0F/\u62E1\u5927\u3057\u307E\u3059(\u65E2\u5B9A: 11)\u3002").addSlider(
      (slider) => slider.setLimits(8, 16, 1).setValue(this.plugin.settings.tableFontSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.tableFontSize = value;
        await this.plugin.saveSettings();
        this.plugin.refreshGanttViews();
      })
    ).addExtraButton(
      (button) => button.setIcon("rotate-ccw").setTooltip("\u65E2\u5B9A\u5024(11px)\u306B\u623B\u3059").onClick(async () => {
        this.plugin.settings.tableFontSize = 11;
        await this.plugin.saveSettings();
        this.plugin.refreshGanttViews();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8868\u793A\u30D5\u30A3\u30EB\u30BF").setHeading().setDesc(
      "\u30AC\u30F3\u30C8\u30D3\u30E5\u30FC\u3067\u8868\u793A\u3059\u308B\u30C1\u30B1\u30C3\u30C8\u306E\u53D6\u5F97\u6761\u4EF6\u3002\u8CA0\u8377\u3092\u6291\u3048\u308B\u305F\u3081\u3001\u3044\u305A\u308C\u304B\u306E\u30D5\u30A3\u30EB\u30BF\u306E\u6307\u5B9A\u304C\u5FC5\u9808\u3067\u3059\u3002\u300C\u89AA\u30C1\u30B1\u30C3\u30C8\u914D\u4E0B\u300D\u306F\u6307\u5B9A\u30C1\u30B1\u30C3\u30C8\u306E\u914D\u4E0B\u30C4\u30EA\u30FC\u5168\u4F53\u3092\u518D\u5E30\u7684\u306B\u53D6\u5F97\u3057\u307E\u3059\u3002\u300C\u4FDD\u5B58\u30AF\u30A8\u30EA\u300D\u306E\u5024\u306F\u30AF\u30A8\u30EAID(Redmine\u306E\u30C1\u30B1\u30C3\u30C8\u4E00\u89A7URL\u306E query_id= \u306E\u6570\u5024)\u3002\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u30B9\u30B3\u30FC\u30D7\u306E\u30AF\u30A8\u30EA\u306F\u300C\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u8B58\u5225\u5B50:\u30AF\u30A8\u30EAID\u300D\u306E\u5F62\u5F0F\u3067\u6307\u5B9A\u3057\u307E\u3059\u3002"
    );
    this.plugin.settings.filters.forEach((filter, index) => {
      const setting = new import_obsidian.Setting(containerEl);
      setting.addText(
        (text) => text.setPlaceholder("\u8868\u793A\u540D").setValue(filter.name).onChange(async (value) => {
          filter.name = value.trim();
          await this.plugin.saveSettings();
        })
      ).addDropdown(
        (dropdown) => dropdown.addOption("parent", "\u89AA\u30C1\u30B1\u30C3\u30C8\u914D\u4E0B").addOption("query", "\u4FDD\u5B58\u30AF\u30A8\u30EA").setValue(filter.type).onChange(async (value) => {
          filter.type = value;
          await this.plugin.saveSettings();
        })
      ).addText(
        (text) => text.setPlaceholder("\u30C1\u30B1\u30C3\u30C8ID / \u30AF\u30A8\u30EAID").setValue(filter.value).onChange(async (value) => {
          filter.value = value.trim();
          await this.plugin.saveSettings();
        })
      ).addExtraButton(
        (button) => button.setIcon("trash").setTooltip("\u524A\u9664").onClick(async () => {
          this.plugin.settings.filters.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    new import_obsidian.Setting(containerEl).addButton(
      (button) => button.setButtonText("\u30D5\u30A3\u30EB\u30BF\u3092\u8FFD\u52A0").onClick(async () => {
        this.plugin.settings.filters.push({
          name: "",
          type: "parent",
          value: ""
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u62C5\u5F53\u8005\u306E\u8272\u5206\u3051").setHeading().setDesc(
      "\u767B\u9332\u3057\u305F\u62C5\u5F53\u8005\u306F\u3001\u8868\u793A\u30D5\u30A3\u30EB\u30BF\u3084\u62C5\u5F53\u8005\u7D5E\u308A\u8FBC\u307F\u306E\u9078\u629E\u306B\u304B\u304B\u308F\u3089\u305A\u5E38\u306B\u3053\u306E\u8272\u3067\u8868\u793A\u3055\u308C\u307E\u3059(\u30AC\u30F3\u30C8\u306E\u30D0\u30FC\u30FB\u30C6\u30FC\u30D6\u30EB\u306E\u62C5\u5F53\u8005\u30C1\u30C3\u30D7)\u3002\u540D\u524D\u306FRedmine\u4E0A\u306E\u8868\u793A\u540D\u3068\u5B8C\u5168\u4E00\u81F4\u3067\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
    );
    this.plugin.settings.assigneeColors.forEach((entry) => {
      new import_obsidian.Setting(containerEl).addText(
        (text) => text.setPlaceholder("\u62C5\u5F53\u8005\u540D(Redmine\u306E\u8868\u793A\u540D)").setValue(entry.name).onChange(async (value) => {
          entry.name = value.trim();
          await this.plugin.saveSettings();
        })
      ).addColorPicker(
        (picker) => picker.setValue(entry.color).onChange(async (value) => {
          entry.color = value;
          await this.plugin.saveSettings();
        })
      ).addExtraButton(
        (button) => button.setIcon("trash").setTooltip("\u524A\u9664").onClick(async () => {
          this.plugin.settings.assigneeColors.remove(entry);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    new import_obsidian.Setting(containerEl).addButton(
      (button) => button.setButtonText("\u62C5\u5F53\u8005\u3092\u8FFD\u52A0").onClick(async () => {
        this.plugin.settings.assigneeColors.push({ name: "", color: "#3f7fd9" });
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/gantt/GanttView.ts
var import_obsidian6 = require("obsidian");

// src/redmine/client.ts
var import_obsidian2 = require("obsidian");
var PAGE_SIZE = 100;
var MAX_ISSUES = 1e4;
var RedmineApiError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
var RedmineClient = class {
  constructor(settings) {
    this.settings = settings;
  }
  get baseUrl() {
    return this.settings.baseUrl.replace(/\/+$/, "");
  }
  issueUrl(issueId) {
    return `${this.baseUrl}/issues/${issueId}`;
  }
  async request(method, path, params, body) {
    var _a;
    if (!this.baseUrl) {
      throw new RedmineApiError(0, "Redmine URL\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    if (!this.settings.apiKey) {
      throw new RedmineApiError(0, "API\u30AD\u30FC\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    const qs = params ? new URLSearchParams(params).toString() : "";
    const url = `${this.baseUrl}${path}${qs ? "?" + qs : ""}`;
    const headers = {
      "X-Redmine-API-Key": this.settings.apiKey,
      Accept: "application/json"
    };
    if (body !== void 0) {
      headers["Content-Type"] = "application/json";
    }
    let response;
    try {
      response = await (0, import_obsidian2.requestUrl)({
        url,
        method,
        headers,
        body: body !== void 0 ? JSON.stringify(body) : void 0,
        throw: false
      });
    } catch (e) {
      throw new RedmineApiError(
        0,
        `Redmine\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093: ${url}
URL\u306E\u8AA4\u308A\u3001\u30CD\u30C3\u30C8\u30EF\u30FC\u30AF\u672A\u5230\u9054\u3001\u307E\u305F\u306F\u81EA\u5DF1\u7F72\u540D\u8A3C\u660E\u66F8\u304C\u539F\u56E0\u306E\u53EF\u80FD\u6027\u304C\u3042\u308A\u307E\u3059\u3002(${String(e)})`
      );
    }
    if (response.status === 401) {
      throw new RedmineApiError(401, "\u8A8D\u8A3C\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002API\u30AD\u30FC\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    }
    if (response.status === 403) {
      throw new RedmineApiError(
        403,
        method === "PUT" ? "\u66F4\u65B0\u304C\u62D2\u5426\u3055\u308C\u307E\u3057\u305F\u3002API\u30AD\u30FC\u306E\u30E6\u30FC\u30B6\u30FC\u306B\u30C1\u30B1\u30C3\u30C8\u306E\u7DE8\u96C6\u6A29\u9650\u304C\u3042\u308B\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002" : "\u30A2\u30AF\u30BB\u30B9\u304C\u62D2\u5426\u3055\u308C\u307E\u3057\u305F\u3002REST API\u304C\u6709\u52B9\u304B(\u7BA1\u7406\u2192\u8A2D\u5B9A\u2192API)\u3001\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u306E\u95B2\u89A7\u6A29\u9650\u304C\u3042\u308B\u304B\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002"
      );
    }
    if (response.status === 404) {
      throw new RedmineApiError(404, `\u898B\u3064\u304B\u308A\u307E\u305B\u3093 (HTTP 404): ${path}`);
    }
    if (response.status === 422) {
      let details = "";
      try {
        const data = response.json;
        details = ((_a = data.errors) != null ? _a : []).join("\n");
      } catch (e) {
      }
      throw new RedmineApiError(422, `Redmine\u304C\u66F4\u65B0\u3092\u53D7\u3051\u4ED8\u3051\u307E\u305B\u3093\u3067\u3057\u305F:
${details || "\u5165\u529B\u5185\u5BB9\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002"}`);
    }
    if (response.status >= 400) {
      throw new RedmineApiError(response.status, `Redmine API\u30A8\u30E9\u30FC (HTTP ${response.status}): ${path}`);
    }
    if (response.status === 204 || !response.text || response.text.length === 0) {
      return void 0;
    }
    return response.json;
  }
  /** 指定条件でチケットをページングしながら全件取得する */
  async fetchIssuesPaged(baseParams) {
    const issues = [];
    let offset = 0;
    for (; ; ) {
      const params = {
        ...baseParams,
        limit: String(PAGE_SIZE),
        offset: String(offset)
      };
      const res = await this.request("GET", "/issues.json", params);
      issues.push(...res.issues);
      offset += res.issues.length;
      if (res.issues.length === 0 || offset >= res.total_count || offset >= MAX_ISSUES) {
        break;
      }
    }
    return issues;
  }
  /**
   * 表示フィルタに応じて対象チケットを取得する。
   * 負荷対策のためプロジェクト全体の取得は提供せず、フィルタの指定が必須。
   */
  async fetchIssues(filter) {
    if (filter.type === "query") {
      return this.fetchQueryIssues(filter.value);
    }
    return this.fetchSubtreeIssues(filter.value);
  }
  /**
   * 保存クエリでの取得。value は「クエリID」または「プロジェクト識別子:クエリID」。
   * 絞り込み条件(ステータス含む)はクエリ側の定義に従うため status_id は付けない。
   *
   * Redmineは query_id 単体指定だとグローバル(全プロジェクト向け)クエリしか
   * 解決しないため、プロジェクト内で保存されたクエリは404になる。その場合は
   * /queries.json から所属プロジェクトを調べて project_id 付きで再試行する。
   */
  async fetchQueryIssues(value) {
    const m = value.trim().match(/^(.+)[::](\d+)$/);
    const params = m ? { project_id: m[1].trim(), query_id: m[2] } : { query_id: value.trim() };
    if (!/^\d+$/.test(params.query_id)) {
      throw new RedmineApiError(
        0,
        `\u4FDD\u5B58\u30AF\u30A8\u30EA\u306E\u6307\u5B9A\u304C\u4E0D\u6B63\u3067\u3059: "${value}"(\u30AF\u30A8\u30EAID\u3001\u307E\u305F\u306F\u300C\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u8B58\u5225\u5B50:\u30AF\u30A8\u30EAID\u300D\u3067\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044)`
      );
    }
    try {
      return await this.fetchIssuesPaged(params);
    } catch (e) {
      if (!(e instanceof RedmineApiError) || e.status !== 404)
        throw e;
      if (params.project_id) {
        throw new RedmineApiError(
          404,
          `\u4FDD\u5B58\u30AF\u30A8\u30EA(ID: ${params.query_id}\u3001\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8: ${params.project_id})\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002
\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u8B58\u5225\u5B50\u3068\u30AF\u30A8\u30EAID\u306E\u7D44\u307F\u5408\u308F\u305B\u3001\u304A\u3088\u3073API\u30AD\u30FC\u306E\u30E6\u30FC\u30B6\u30FC\u304C\u305D\u306E\u30AF\u30A8\u30EA\u3092\u4F7F\u3048\u308B\u304B\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002`
        );
      }
      const queryId = Number(params.query_id);
      const found = await this.findQuery(queryId);
      if (found && found.project_id) {
        return this.fetchIssuesPaged({
          query_id: params.query_id,
          project_id: String(found.project_id)
        });
      }
      if (found) {
        throw new RedmineApiError(
          404,
          `\u4FDD\u5B58\u30AF\u30A8\u30EA\u300C${found.name}\u300D(ID: ${queryId})\u306F\u5B58\u5728\u3057\u307E\u3059\u304C\u3001\u30C1\u30B1\u30C3\u30C8\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F(HTTP 404)\u3002`
        );
      }
      throw new RedmineApiError(
        404,
        `\u4FDD\u5B58\u30AF\u30A8\u30EA(ID: ${queryId})\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002\u6B21\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044:
\u30FB\u30AF\u30A8\u30EAID\u304C\u6B63\u3057\u3044\u304B(Redmine\u306E\u30C1\u30B1\u30C3\u30C8\u4E00\u89A7URL\u306E query_id= \u306E\u6570\u5024)
\u30FBAPI\u30AD\u30FC\u306E\u30E6\u30FC\u30B6\u30FC\u304C\u305D\u306E\u30AF\u30A8\u30EA\u3092\u4F7F\u3048\u308B\u304B(\u81EA\u5206\u306E\u30AF\u30A8\u30EA\u3001\u307E\u305F\u306F\u516C\u958B\u30AF\u30A8\u30EA\u306E\u307F)`
      );
    }
  }
  /** /queries.json から指定IDのクエリを探す(見えるクエリのみ返る) */
  async findQuery(queryId) {
    let offset = 0;
    for (; ; ) {
      const res = await this.request("GET", "/queries.json", {
        limit: String(PAGE_SIZE),
        offset: String(offset)
      });
      const hit = res.queries.find((q) => q.id === queryId);
      if (hit)
        return hit;
      offset += res.queries.length;
      if (res.queries.length === 0 || offset >= res.total_count)
        return null;
    }
  }
  /**
   * 親チケット配下のツリー全体を取得する。
   * parent_id の「~」演算子(指定チケットの全子孫を再帰的に返す)で一括取得し、
   * 対応していないRedmineでは1親ずつ辿るBFSにフォールバックする。
   * 完了チケットの表示/非表示はビュー側で切り替えるため、取得は常に全ステータスで行う。
   */
  async fetchSubtreeIssues(value) {
    const rootId = Number(value.trim());
    if (!Number.isInteger(rootId) || rootId <= 0) {
      throw new RedmineApiError(0, `\u89AA\u30C1\u30B1\u30C3\u30C8ID\u304C\u4E0D\u6B63\u3067\u3059: "${value}"(\u30C1\u30B1\u30C3\u30C8\u756A\u53F7\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044)`);
    }
    let root;
    try {
      const rootRes = await this.request("GET", `/issues/${rootId}.json`);
      root = rootRes.issue;
    } catch (e) {
      if (e instanceof RedmineApiError && e.status === 404) {
        throw new RedmineApiError(
          404,
          `\u30C1\u30B1\u30C3\u30C8 #${rootId} \u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3002\u30C1\u30B1\u30C3\u30C8\u756A\u53F7\u3068\u95B2\u89A7\u6A29\u9650\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002`
        );
      }
      throw e;
    }
    let descendants = null;
    try {
      descendants = await this.fetchIssuesPaged({
        parent_id: `~${rootId}`,
        status_id: "*",
        sort: "start_date:asc,id:asc"
      });
    } catch (e) {
      descendants = null;
    }
    if (descendants === null || descendants.length === 0) {
      descendants = await this.crawlDescendants(rootId);
    }
    const seen = /* @__PURE__ */ new Set([rootId]);
    const result = [root];
    for (const issue of descendants) {
      if (!seen.has(issue.id)) {
        seen.add(issue.id);
        result.push(issue);
      }
    }
    return result;
  }
  /**
   * フォールバック: parent_id を1件ずつ指定して階層を辿る。
   * Redmineの parent_id フィルタは「a|b」の複数指定でも先頭の値しか評価しないため、
   * 必ず1リクエスト1親で問い合わせる。
   */
  async crawlDescendants(rootId) {
    const result = [];
    const seen = /* @__PURE__ */ new Set([rootId]);
    let frontier = [rootId];
    while (frontier.length > 0 && result.length < MAX_ISSUES) {
      const next = [];
      for (const parentId of frontier) {
        const children = await this.fetchIssuesPaged({
          parent_id: String(parentId),
          status_id: "*",
          sort: "start_date:asc,id:asc"
        });
        for (const child of children) {
          if (!seen.has(child.id)) {
            seen.add(child.id);
            result.push(child);
            next.push(child.id);
          }
        }
      }
      frontier = next;
    }
    return result;
  }
  /** チケットを1件取得する(編集モーダルで最新状態を表示するために使う) */
  async fetchIssue(issueId) {
    const res = await this.request("GET", `/issues/${issueId}.json`);
    return res.issue;
  }
  /** 全ステータスの一覧。ワークフロー上の遷移可否は含まれない(不可な遷移は更新時に422で返る) */
  async fetchStatuses() {
    const res = await this.request("GET", "/issue_statuses.json");
    return res.issue_statuses;
  }
  /** プロジェクトのメンバー(担当者候補)。権限等で取得できない場合は呼び出し側でフォールバックする */
  async fetchProjectMembers(projectId) {
    var _a;
    const members = [];
    const seen = /* @__PURE__ */ new Set();
    let offset = 0;
    for (; ; ) {
      const res = await this.request(
        "GET",
        `/projects/${projectId}/memberships.json`,
        { limit: String(PAGE_SIZE), offset: String(offset) }
      );
      for (const membership of res.memberships) {
        const ref = (_a = membership.user) != null ? _a : membership.group;
        if (ref && !seen.has(ref.id)) {
          seen.add(ref.id);
          members.push(ref);
        }
      }
      offset += res.memberships.length;
      if (res.memberships.length === 0 || offset >= res.total_count)
        break;
    }
    return members;
  }
  /** チケットのフィールドを更新する(変更するフィールドのみ渡す) */
  async updateIssue(issueId, payload) {
    await this.request("PUT", `/issues/${issueId}.json`, void 0, { issue: payload });
  }
  /** 接続テスト等に使うプロジェクト一覧取得 */
  async fetchProjects() {
    const res = await this.request("GET", "/projects.json", {
      limit: String(PAGE_SIZE)
    });
    return res.projects;
  }
};

// src/redmine/mapper.ts
var DELIVERY_FIELD_NAME = "\u7D0D\u671F";
function parseDate(s) {
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}
function toTask(issue) {
  var _a, _b, _c, _d, _e, _f, _g;
  let start = null;
  let due = null;
  let startIsFallback = false;
  let dueIsFallback = false;
  if (issue.start_date) {
    start = parseDate(issue.start_date);
  }
  if (issue.due_date) {
    due = parseDate(issue.due_date);
  }
  if (!start && due) {
    const created = new Date(issue.created_on);
    start = new Date(created.getFullYear(), created.getMonth(), created.getDate());
    if (start > due)
      start = due;
    startIsFallback = true;
  }
  if (start && !due) {
    due = start;
    dueIsFallback = true;
  }
  const deliveryValue = (_b = (_a = issue.custom_fields) == null ? void 0 : _a.find((f) => f.name === DELIVERY_FIELD_NAME)) == null ? void 0 : _b.value;
  return {
    id: issue.id,
    subject: issue.subject,
    start,
    due,
    doneRatio: (_c = issue.done_ratio) != null ? _c : 0,
    assignee: (_e = (_d = issue.assigned_to) == null ? void 0 : _d.name) != null ? _e : "",
    status: issue.status.name,
    tracker: issue.tracker.name,
    project: issue.project.name,
    delivery: Array.isArray(deliveryValue) ? deliveryValue.join(", ") : deliveryValue != null ? deliveryValue : "",
    parentId: (_g = (_f = issue.parent) == null ? void 0 : _f.id) != null ? _g : null,
    depth: 0,
    isContext: false,
    startIsFallback,
    dueIsFallback,
    isClosed: !!issue.closed_on
  };
}
function buildGanttModel(issues, contextIds) {
  var _a;
  const all = issues.map(toTask);
  if (contextIds) {
    for (const task of all) {
      task.isContext = contextIds.has(task.id);
    }
  }
  const byId = new Map(all.map((t) => [t.id, t]));
  const children = /* @__PURE__ */ new Map();
  const roots = [];
  for (const task of all) {
    if (task.parentId !== null && byId.has(task.parentId)) {
      const list = (_a = children.get(task.parentId)) != null ? _a : [];
      list.push(task);
      children.set(task.parentId, list);
    } else {
      roots.push(task);
    }
  }
  const ordered = [];
  const visit = (task, depth) => {
    var _a2;
    task.depth = depth;
    ordered.push(task);
    for (const child of (_a2 = children.get(task.id)) != null ? _a2 : []) {
      visit(child, depth + 1);
    }
  };
  for (const root of roots)
    visit(root, 0);
  return { tasks: ordered };
}

// src/issue/IssueEditModal.ts
var import_obsidian3 = require("obsidian");
var IssueEditModal = class extends import_obsidian3.Modal {
  constructor(app, client, issueId, onSaved) {
    super(app);
    this.issue = null;
    this.statuses = [];
    this.members = [];
    this.saving = false;
    // フォームの入力値
    this.statusId = 0;
    this.assigneeId = "";
    // user id の文字列。空は未割当
    this.startDate = "";
    this.dueDate = "";
    this.delivery = "";
    this.doneRatio = 0;
    this.deliveryFieldId = null;
    this.client = client;
    this.issueId = issueId;
    this.onSaved = onSaved;
  }
  async onOpen() {
    var _a, _b, _c, _d, _e;
    const { contentEl } = this;
    contentEl.createEl("h3", { text: `#${this.issueId} \u3092\u8AAD\u307F\u8FBC\u307F\u4E2D\u2026` });
    try {
      const [issue, statuses] = await Promise.all([
        this.client.fetchIssue(this.issueId),
        this.client.fetchStatuses()
      ]);
      this.issue = issue;
      this.statuses = statuses;
      try {
        this.members = await this.client.fetchProjectMembers(issue.project.id);
      } catch (e) {
        this.members = [];
      }
      if (issue.assigned_to && !this.members.some((m) => m.id === issue.assigned_to.id)) {
        this.members.unshift(issue.assigned_to);
      }
      this.statusId = issue.status.id;
      this.assigneeId = issue.assigned_to ? String(issue.assigned_to.id) : "";
      this.startDate = (_a = issue.start_date) != null ? _a : "";
      this.dueDate = (_b = issue.due_date) != null ? _b : "";
      this.doneRatio = (_c = issue.done_ratio) != null ? _c : 0;
      const deliveryField = (_d = issue.custom_fields) == null ? void 0 : _d.find((f) => f.name === DELIVERY_FIELD_NAME);
      if (deliveryField) {
        this.deliveryFieldId = deliveryField.id;
        this.delivery = Array.isArray(deliveryField.value) ? deliveryField.value.join(", ") : (_e = deliveryField.value) != null ? _e : "";
      }
      this.renderForm();
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      contentEl.empty();
      contentEl.createEl("h3", { text: `#${this.issueId} \u306E\u8AAD\u307F\u8FBC\u307F\u306B\u5931\u6557` });
      contentEl.createDiv({ cls: "rg-error", text: message });
    }
  }
  renderForm() {
    const issue = this.issue;
    if (!issue)
      return;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: `#${issue.id} ${issue.subject}` });
    contentEl.createDiv({
      cls: "rg-edit-meta",
      text: `${issue.project.name} / ${issue.tracker.name}`
    });
    new import_obsidian3.Setting(contentEl).setName("\u30B9\u30C6\u30FC\u30BF\u30B9").addDropdown((dropdown) => {
      for (const status of this.statuses) {
        dropdown.addOption(String(status.id), status.name);
      }
      dropdown.setValue(String(this.statusId)).onChange((value) => {
        this.statusId = Number(value);
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u62C5\u5F53\u8005").addDropdown((dropdown) => {
      dropdown.addOption("", "(\u672A\u5272\u5F53)");
      for (const member of this.members) {
        dropdown.addOption(String(member.id), member.name);
      }
      dropdown.setValue(this.assigneeId).onChange((value) => {
        this.assigneeId = value;
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u958B\u59CB\u65E5").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.startDate).onChange((value) => {
        this.startDate = value;
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u671F\u65E5").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.dueDate).onChange((value) => {
        this.dueDate = value;
      });
    });
    if (this.deliveryFieldId !== null) {
      new import_obsidian3.Setting(contentEl).setName("\u7D0D\u671F").addText((text) => {
        text.inputEl.type = "date";
        text.setValue(this.delivery).onChange((value) => {
          this.delivery = value;
        });
      });
    }
    new import_obsidian3.Setting(contentEl).setName("\u9032\u6357\u7387").addDropdown((dropdown) => {
      for (let ratio = 0; ratio <= 100; ratio += 10) {
        dropdown.addOption(String(ratio), `${ratio}%`);
      }
      dropdown.setValue(String(this.doneRatio)).onChange((value) => {
        this.doneRatio = Number(value);
      });
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u4FDD\u5B58").setCta().onClick(() => void this.save())
    ).addButton((button) => button.setButtonText("\u30AD\u30E3\u30F3\u30BB\u30EB").onClick(() => this.close()));
  }
  /** 変更されたフィールドだけを集めた更新ペイロード。変更なしなら null */
  buildPayload() {
    var _a, _b, _c, _d, _e, _f;
    const issue = this.issue;
    if (!issue)
      return null;
    const payload = {};
    if (this.statusId !== issue.status.id)
      payload.status_id = this.statusId;
    const currentAssignee = issue.assigned_to ? String(issue.assigned_to.id) : "";
    if (this.assigneeId !== currentAssignee) {
      payload.assigned_to_id = this.assigneeId === "" ? "" : Number(this.assigneeId);
    }
    if (this.startDate !== ((_a = issue.start_date) != null ? _a : ""))
      payload.start_date = this.startDate;
    if (this.dueDate !== ((_b = issue.due_date) != null ? _b : ""))
      payload.due_date = this.dueDate;
    if (((_c = this.doneRatio) != null ? _c : 0) !== ((_d = issue.done_ratio) != null ? _d : 0))
      payload.done_ratio = this.doneRatio;
    if (this.deliveryFieldId !== null) {
      const field = (_e = issue.custom_fields) == null ? void 0 : _e.find((f) => f.id === this.deliveryFieldId);
      const current = Array.isArray(field == null ? void 0 : field.value) ? field.value.join(", ") : (_f = field == null ? void 0 : field.value) != null ? _f : "";
      if (this.delivery !== current) {
        payload.custom_fields = [{ id: this.deliveryFieldId, value: this.delivery }];
      }
    }
    return Object.keys(payload).length > 0 ? payload : null;
  }
  async save() {
    if (this.saving || !this.issue)
      return;
    const payload = this.buildPayload();
    if (!payload) {
      this.close();
      return;
    }
    this.saving = true;
    try {
      await this.client.updateIssue(this.issueId, payload);
      const updated = await this.client.fetchIssue(this.issueId);
      new import_obsidian3.Notice(`#${this.issueId} \u3092\u66F4\u65B0\u3057\u307E\u3057\u305F`);
      this.onSaved(updated);
      this.close();
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      new import_obsidian3.Notice(`Redmine Gantt: ${message}`, 8e3);
    } finally {
      this.saving = false;
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/plan/PlanModal.ts
var import_obsidian4 = require("obsidian");
var PlanModal = class extends import_obsidian4.Modal {
  constructor(app, items, onSave) {
    super(app);
    this.items = items.map((item) => ({ ...item }));
    this.onSave = onSave;
  }
  onOpen() {
    this.render();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "\u5168\u4F53\u4E88\u5B9A\u306E\u7DE8\u96C6" });
    contentEl.createEl("p", {
      cls: "rg-plan-desc",
      text: "Redmine\u3068\u306F\u72EC\u7ACB\u3057\u305F\u4E88\u5B9A\u3067\u3059\u3002\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u306E\u6700\u4E0A\u6BB5\u306B\u8868\u793A\u3055\u308C\u307E\u3059\u3002"
    });
    this.items.forEach((item, index) => {
      const setting = new import_obsidian4.Setting(contentEl);
      setting.settingEl.addClass("rg-plan-setting");
      setting.addText((text) => {
        text.setPlaceholder("\u4E88\u5B9A\u540D").setValue(item.name).onChange((value) => {
          item.name = value.trim();
        });
        text.inputEl.addClass("rg-plan-name-input");
      }).addText((text) => {
        text.inputEl.type = "date";
        text.setValue(item.start).onChange((value) => {
          item.start = value;
        });
      }).addText((text) => {
        text.inputEl.type = "date";
        text.setValue(item.end).onChange((value) => {
          item.end = value;
        });
      }).addDropdown((dropdown) => {
        for (const [value, label] of Object.entries(PLAN_STATUS_LABELS)) {
          dropdown.addOption(value, label);
        }
        dropdown.setValue(item.status).onChange((value) => {
          item.status = value;
        });
      }).addExtraButton(
        (button) => button.setIcon("trash").setTooltip("\u524A\u9664").onClick(() => {
          this.items.splice(index, 1);
          this.render();
        })
      );
    });
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u4E88\u5B9A\u3092\u8FFD\u52A0").onClick(() => {
        this.items.push({
          id: `plan-${Date.now()}-${Math.floor(Math.random() * 1e4)}`,
          name: "",
          start: "",
          end: "",
          status: "todo"
        });
        this.render();
      })
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (button) => button.setButtonText("\u4FDD\u5B58").setCta().onClick(() => {
        this.onSave(this.items.filter((item) => item.name !== ""));
        this.close();
      })
    ).addButton((button) => button.setButtonText("\u30AD\u30E3\u30F3\u30BB\u30EB").onClick(() => this.close()));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/gantt/scale.ts
var MS_PER_DAY = 24 * 60 * 60 * 1e3;
var PX_PER_DAY = {
  day: 32,
  week: 12,
  month: 4
};
function startOfDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function addDays(d, days) {
  const r = new Date(d);
  r.setDate(r.getDate() + days);
  return r;
}
function diffDays(from, to) {
  return Math.round((startOfDay(to).getTime() - startOfDay(from).getTime()) / MS_PER_DAY);
}
function monthRange(year, month0, months) {
  const start = new Date(year, month0, 1);
  const end = new Date(year, month0 + months, 0);
  return { start, end, days: diffDays(start, end) };
}
function computeTicks(range, scale) {
  const ppd = PX_PER_DAY[scale];
  const major = [];
  const minor = [];
  const gridX = [];
  for (let i = 0; i <= range.days; i++) {
    const d = addDays(range.start, i);
    const x = i * ppd;
    if (d.getDate() === 1 || i === 0) {
      major.push({ x, label: `${d.getFullYear()}/${d.getMonth() + 1}` });
      if (scale === "month")
        gridX.push(x);
    }
    if (scale === "day") {
      minor.push({ x, label: String(d.getDate()) });
      gridX.push(x);
    } else if (scale === "week" && d.getDay() === 1) {
      minor.push({ x, label: `${d.getMonth() + 1}/${d.getDate()}` });
      gridX.push(x);
    }
  }
  return { major, minor, gridX };
}
function weekendBands(range, scale) {
  if (scale !== "day")
    return [];
  const ppd = PX_PER_DAY[scale];
  const bands = [];
  for (let i = 0; i <= range.days; i++) {
    const d = addDays(range.start, i);
    const day = d.getDay();
    if (day === 0 || day === 6) {
      bands.push({ x: i * ppd, w: ppd });
    }
  }
  return bands;
}

// src/gantt/renderer.ts
var HEADER_HEIGHT = 40;
var DEFAULT_LEFT_WIDTH = 480;
var MIN_LEFT_WIDTH = 200;
var INDENT = 16;
var SVG_NS = "http://www.w3.org/2000/svg";
function svg(tag, attrs = {}) {
  const el = document.createElementNS(SVG_NS, tag);
  for (const [k, v] of Object.entries(attrs)) {
    el.setAttribute(k, String(v));
  }
  return el;
}
function rowHeightFor(fontSize) {
  return Math.max(16, Math.round(fontSize * 2));
}
function clipSpan(start, end, range) {
  if (end < range.start || start > range.end)
    return null;
  return {
    s: start < range.start ? range.start : start,
    e: end > range.end ? range.end : end
  };
}
function renderGantt(container, model, plans, scale, range, opts) {
  var _a, _b;
  container.empty();
  if (model.tasks.length === 0 && plans.length === 0) {
    container.createDiv({ cls: "rg-empty", text: "\u8868\u793A\u3067\u304D\u308B\u30C1\u30B1\u30C3\u30C8\u304C\u3042\u308A\u307E\u305B\u3093\u3002" });
    return;
  }
  const ppd = PX_PER_DAY[scale];
  const chartWidth = (range.days + 1) * ppd;
  const rowHeight = rowHeightFor(opts.fontSize);
  const barPadding = Math.max(3, Math.round(rowHeight * 0.22));
  const datedPlans = plans.filter((p) => p.start !== null && p.end !== null).sort((a, b) => a.start.getTime() - b.start.getTime());
  const laneEnds = [];
  const planLane = /* @__PURE__ */ new Map();
  for (const plan of datedPlans) {
    const isSingleDay = diffDays(plan.start, plan.end) === 0;
    const labelDays = isSingleDay ? Math.ceil((plan.name.length * opts.fontSize + rowHeight) / ppd) : 0;
    const effectiveEnd = labelDays > 0 ? addDays(plan.end, labelDays) : plan.end;
    let lane = laneEnds.findIndex((end) => plan.start > end);
    if (lane === -1) {
      lane = laneEnds.length;
      laneEnds.push(effectiveEnd);
    } else {
      laneEnds[lane] = effectiveEnd;
    }
    planLane.set(plan, lane);
  }
  const planLaneCount = laneEnds.length;
  const topHeight = HEADER_HEIGHT + planLaneCount * rowHeight;
  const tasksHeight = model.tasks.length * rowHeight;
  const leftWidth = (_a = opts.leftWidth) != null ? _a : DEFAULT_LEFT_WIDTH;
  const ticks = computeTicks(range, scale);
  const today = /* @__PURE__ */ new Date();
  const todayX = today >= range.start && diffDays(range.start, today) <= range.days ? diffDays(range.start, today) * ppd + ppd / 2 : null;
  const leftEls = [];
  const attachResizer = (host) => {
    const resizer = host.createDiv({ cls: "rg-left-resizer" });
    resizer.addEventListener("mousedown", (e) => {
      e.preventDefault();
      const startX = e.clientX;
      const startWidth = host.getBoundingClientRect().width;
      const onMove = (ev) => {
        var _a2;
        const width = Math.max(MIN_LEFT_WIDTH, startWidth + ev.clientX - startX);
        for (const el of leftEls) {
          el.style.width = `${width}px`;
        }
        (_a2 = opts.onLeftWidthChange) == null ? void 0 : _a2.call(opts, width);
      };
      const onUp = () => {
        document.removeEventListener("mousemove", onMove);
        document.removeEventListener("mouseup", onUp);
        document.body.removeClass("rg-resizing");
      };
      document.body.addClass("rg-resizing");
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
    });
  };
  const stickyTop = container.createDiv({ cls: "rg-sticky-top" });
  const leftTop = stickyTop.createDiv({ cls: "rg-left rg-left-top" });
  leftTop.style.width = `${leftWidth}px`;
  leftTop.style.fontSize = `${opts.fontSize}px`;
  leftEls.push(leftTop);
  attachResizer(leftTop);
  const leftHeader = leftTop.createDiv({ cls: "rg-left-header" });
  leftHeader.style.height = `${HEADER_HEIGHT}px`;
  leftHeader.setText("\u30C1\u30B1\u30C3\u30C8");
  if (planLaneCount > 0) {
    const planLabel = leftTop.createDiv({ cls: "rg-left-row rg-plan-row rg-plan-label" });
    planLabel.style.height = `${planLaneCount * rowHeight}px`;
    planLabel.style.paddingLeft = "8px";
    planLabel.setText("\u5168\u4F53\u4E88\u5B9A");
  }
  const chartTop = stickyTop.createDiv({ cls: "rg-chart" });
  const topSvg = svg("svg", {
    width: chartWidth,
    height: topHeight,
    viewBox: `0 0 ${chartWidth} ${topHeight}`
  });
  chartTop.appendChild(topSvg);
  if (planLaneCount > 0) {
    topSvg.appendChild(
      svg("rect", {
        x: 0,
        y: HEADER_HEIGHT,
        width: chartWidth,
        height: planLaneCount * rowHeight,
        class: "rg-plan-area"
      })
    );
  }
  for (const x of ticks.gridX) {
    topSvg.appendChild(
      svg("line", { x1: x, y1: HEADER_HEIGHT, x2: x, y2: topHeight, class: "rg-grid" })
    );
  }
  for (let i = 0; i <= planLaneCount; i++) {
    const y = HEADER_HEIGHT + i * rowHeight;
    topSvg.appendChild(
      svg("line", {
        x1: 0,
        y1: y,
        x2: chartWidth,
        y2: y,
        class: i === planLaneCount ? "rg-separator" : "rg-grid"
      })
    );
  }
  for (const tick of ticks.major) {
    const t = svg("text", { x: tick.x + 4, y: 15, class: "rg-tick-major" });
    t.textContent = tick.label;
    topSvg.appendChild(t);
    topSvg.appendChild(
      svg("line", { x1: tick.x, y1: 0, x2: tick.x, y2: HEADER_HEIGHT, class: "rg-grid" })
    );
  }
  for (const tick of ticks.minor) {
    const t = svg("text", { x: tick.x + 3, y: 33, class: "rg-tick-minor" });
    t.textContent = tick.label;
    topSvg.appendChild(t);
  }
  for (const plan of datedPlans) {
    const lane = (_b = planLane.get(plan)) != null ? _b : 0;
    const y = HEADER_HEIGHT + lane * rowHeight + barPadding;
    const h = rowHeight - barPadding * 2;
    const textBaseline = y + Math.round(h / 2 + opts.fontSize * 0.35);
    const group = svg("g", {});
    const title = svg("title");
    title.textContent = planTooltip(plan);
    group.appendChild(title);
    if (diffDays(plan.start, plan.end) === 0) {
      if (plan.start < range.start || plan.start > range.end)
        continue;
      const cx = diffDays(range.start, plan.start) * ppd + ppd / 2;
      const half = Math.max(5, Math.round(h / 2));
      group.appendChild(
        svg("polygon", {
          points: `${cx - half},${y} ${cx + half},${y} ${cx},${y + h}`,
          class: `rg-plan-marker rg-plan-${plan.status}`
        })
      );
      const label = svg("text", {
        x: cx + half + 4,
        y: textBaseline,
        "font-size": opts.fontSize,
        class: `rg-plan-marker-label rg-plan-${plan.status}`
      });
      label.textContent = plan.name;
      group.appendChild(label);
    } else {
      const span = clipSpan(plan.start, plan.end, range);
      if (!span)
        continue;
      const x = diffDays(range.start, span.s) * ppd;
      const w = Math.max((diffDays(span.s, span.e) + 1) * ppd, 4);
      group.appendChild(
        svg("rect", { x, y, width: w, height: h, rx: 3, class: `rg-plan-bar rg-plan-${plan.status}` })
      );
      const maxChars = Math.floor((w - 10) / opts.fontSize);
      if (maxChars >= 2) {
        const name = plan.name.length > maxChars ? plan.name.slice(0, maxChars - 1) + "\u2026" : plan.name;
        const label = svg("text", {
          x: x + 6,
          y: textBaseline,
          "font-size": opts.fontSize,
          class: "rg-plan-bar-label"
        });
        label.textContent = name;
        group.appendChild(label);
      }
    }
    topSvg.appendChild(group);
  }
  if (todayX !== null) {
    topSvg.appendChild(
      svg("line", { x1: todayX, y1: 0, x2: todayX, y2: topHeight, class: "rg-today" })
    );
  }
  const body = container.createDiv({ cls: "rg-body" });
  const left = body.createDiv({ cls: "rg-left" });
  left.style.width = `${leftWidth}px`;
  left.style.fontSize = `${opts.fontSize}px`;
  leftEls.push(left);
  attachResizer(left);
  for (const task of model.tasks) {
    const row = left.createDiv({ cls: "rg-left-row" });
    row.style.height = `${rowHeight}px`;
    row.style.paddingLeft = `${8 + task.depth * INDENT}px`;
    row.createEl("a", {
      cls: "rg-id-link",
      text: `#${task.id}`,
      href: opts.issueUrl(task.id)
    });
    row.createSpan({ cls: "rg-tracker", text: task.tracker });
    const link = row.createEl("a", {
      cls: "rg-issue-link",
      text: task.subject,
      href: opts.issueUrl(task.id)
    });
    link.setAttr("title", taskTooltip(task));
    if (task.isClosed)
      row.addClass("rg-row-closed");
    if (task.isContext)
      row.addClass("rg-row-context");
    if (task.assignee) {
      const chip = row.createSpan({ cls: "rg-assignee-chip", text: task.assignee });
      const color = task.isContext ? null : opts.assigneeColor(task.assignee);
      if (color) {
        chip.style.backgroundColor = color;
        chip.addClass("rg-assignee-chip-colored");
      }
    }
  }
  const chart = body.createDiv({ cls: "rg-chart" });
  const root = svg("svg", {
    width: chartWidth,
    height: tasksHeight,
    viewBox: `0 0 ${chartWidth} ${tasksHeight}`
  });
  chart.appendChild(root);
  for (const band of weekendBands(range, scale)) {
    root.appendChild(
      svg("rect", { x: band.x, y: 0, width: band.w, height: tasksHeight, class: "rg-weekend" })
    );
  }
  for (const x of ticks.gridX) {
    root.appendChild(svg("line", { x1: x, y1: 0, x2: x, y2: tasksHeight, class: "rg-grid" }));
  }
  for (let i = 0; i <= model.tasks.length; i++) {
    const y = i * rowHeight;
    root.appendChild(svg("line", { x1: 0, y1: y, x2: chartWidth, y2: y, class: "rg-grid" }));
  }
  model.tasks.forEach((task, i) => {
    if (!task.start || !task.due)
      return;
    const span = clipSpan(task.start, task.due, range);
    if (!span)
      return;
    const x = diffDays(range.start, span.s) * ppd;
    const w = Math.max((diffDays(span.s, span.e) + 1) * ppd, 4);
    const y = i * rowHeight + barPadding;
    const h = rowHeight - barPadding * 2;
    const group = svg("g", { class: "rg-bar-group" });
    const assigneeColor = task.assignee && !task.isContext ? opts.assigneeColor(task.assignee) : null;
    const barClass = "rg-bar" + (task.isClosed ? " rg-bar-closed" : "") + (task.isContext ? " rg-bar-context" : "") + (task.startIsFallback || task.dueIsFallback ? " rg-bar-fallback" : "");
    const bar = svg("rect", { x, y, width: w, height: h, rx: 3, class: barClass });
    if (assigneeColor && !task.isClosed)
      bar.style.fill = assigneeColor;
    const title = svg("title");
    title.textContent = taskTooltip(task);
    bar.appendChild(title);
    group.appendChild(bar);
    if (task.doneRatio > 0) {
      const progress = svg("rect", {
        x,
        y,
        width: w * Math.min(task.doneRatio, 100) / 100,
        height: h,
        rx: 3,
        class: "rg-bar-progress" + (task.isClosed ? " rg-bar-closed" : "") + (task.isContext ? " rg-bar-context" : "")
      });
      if (assigneeColor && !task.isClosed)
        progress.style.fill = assigneeColor;
      group.appendChild(progress);
    }
    group.addEventListener("click", () => {
      window.open(opts.issueUrl(task.id));
    });
    root.appendChild(group);
  });
  if (todayX !== null) {
    root.appendChild(
      svg("line", { x1: todayX, y1: 0, x2: todayX, y2: tasksHeight, class: "rg-today" })
    );
  }
}
function formatDate(d) {
  if (!d)
    return "-";
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate()
  ).padStart(2, "0")}`;
}
function taskTooltip(task) {
  const lines = [
    `#${task.id} ${task.subject}`,
    `${task.tracker} / ${task.status}`,
    `\u671F\u9593: ${formatDate(task.start)}${task.startIsFallback ? "(\u63A8\u5B9A)" : ""} \u301C ${formatDate(task.due)}${task.dueIsFallback ? "(\u672A\u8A2D\u5B9A)" : ""}`,
    `\u9032\u6357: ${task.doneRatio}%`
  ];
  if (task.assignee)
    lines.push(`\u62C5\u5F53: ${task.assignee}`);
  if (task.isContext)
    lines.push("(\u7D5E\u308A\u8FBC\u307F\u6761\u4EF6\u5916\u306E\u89AA\u3002\u30C4\u30EA\u30FC\u8868\u793A\u306E\u305F\u3081\u53C2\u8003\u8868\u793A)");
  return lines.join("\n");
}
function planTooltip(plan) {
  return [
    plan.name,
    `\u671F\u9593: ${formatDate(plan.start)} \u301C ${formatDate(plan.end)}`,
    `\u72B6\u614B: ${PLAN_STATUS_LABELS[plan.status]}`
  ].join("\n");
}

// src/gantt/table.ts
var import_obsidian5 = require("obsidian");
var INDENT2 = 16;
var MIN_COL_WIDTH = 48;
var COLUMNS = [
  { label: "#", width: 72 },
  { label: "\u30C8\u30E9\u30C3\u30AB\u30FC", width: 100 },
  { label: "\u984C\u540D", width: 360 },
  { label: "\u30B9\u30C6\u30FC\u30BF\u30B9", width: 120 },
  { label: "\u62C5\u5F53\u8005", width: 110 },
  { label: "\u72B6\u6CC1", width: 104 },
  { label: "\u958B\u59CB\u65E5", width: 96, cls: "rg-td-date" },
  { label: "\u671F\u65E5", width: 96, cls: "rg-td-date" },
  { label: "\u7D0D\u671F", width: 96, cls: "rg-td-date" },
  { label: "\u9032\u6357", width: 96 },
  { label: "", width: 44 }
];
function defaultTableWidths() {
  return COLUMNS.map((c) => c.width);
}
function renderTable(container, model, opts) {
  var _a, _b, _c;
  container.empty();
  let tasks = model.tasks;
  const query = ((_a = opts.subjectFilter) != null ? _a : "").trim().toLowerCase();
  if (query) {
    tasks = tasks.filter((task) => task.subject.toLowerCase().includes(query));
  }
  const situation = (_b = opts.situationFilter) != null ? _b : "all";
  if (situation !== "all") {
    tasks = tasks.filter((task) => matchesSituationFilter(task, situation));
  }
  if (tasks.length === 0) {
    container.createDiv({ cls: "rg-empty", text: "\u8868\u793A\u3067\u304D\u308B\u30C1\u30B1\u30C3\u30C8\u304C\u3042\u308A\u307E\u305B\u3093\u3002" });
    return;
  }
  const wrap = container.createDiv({ cls: "rg-table-wrap" });
  const colRegistry = [];
  const groupBy = (_c = opts.groupBy) != null ? _c : "none";
  if (groupBy === "none") {
    buildTable(wrap, tasks, opts, colRegistry);
    return;
  }
  const groups = /* @__PURE__ */ new Map();
  for (const task of tasks) {
    const key = groupBy === "tracker" ? task.tracker : task.assignee;
    const list = groups.get(key);
    if (list) {
      list.push(task);
    } else {
      groups.set(key, [task]);
    }
  }
  const keys = Array.from(groups.keys()).sort((a, b) => {
    if (a === "")
      return 1;
    if (b === "")
      return -1;
    return a.localeCompare(b, "ja");
  });
  for (const key of keys) {
    const list = groups.get(key);
    const label = key !== "" ? key : groupBy === "assignee" ? "(\u62C5\u5F53\u8005\u306A\u3057)" : "(\u30C8\u30E9\u30C3\u30AB\u30FC\u306A\u3057)";
    const title = wrap.createDiv({ cls: "rg-table-group-title" });
    title.style.fontSize = `${opts.fontSize + 2}px`;
    title.setText(`${label}(${list.length}\u4EF6)`);
    buildTable(wrap, list, opts, colRegistry);
  }
}
function buildTable(wrap, tasks, opts, colRegistry) {
  const table = wrap.createEl("table", { cls: "rg-table" });
  table.style.fontSize = `${opts.fontSize}px`;
  const colgroup = table.createEl("colgroup");
  const cols = COLUMNS.map((_, i) => {
    const col = colgroup.createEl("col");
    col.style.width = `${opts.widths[i]}px`;
    return col;
  });
  colRegistry.push(cols);
  const thead = table.createEl("thead");
  const headRow = thead.createEl("tr");
  COLUMNS.forEach((column, i) => {
    const th = headRow.createEl("th", { text: column.label });
    const resizer = th.createDiv({ cls: "rg-col-resizer" });
    resizer.addEventListener("mousedown", (e) => {
      e.preventDefault();
      const startX = e.clientX;
      const startWidth = opts.widths[i];
      const onMove = (ev) => {
        opts.widths[i] = Math.max(MIN_COL_WIDTH, startWidth + ev.clientX - startX);
        for (const tableCols of colRegistry) {
          tableCols[i].style.width = `${opts.widths[i]}px`;
        }
      };
      const onUp = () => {
        document.removeEventListener("mousemove", onMove);
        document.removeEventListener("mouseup", onUp);
        document.body.removeClass("rg-resizing");
      };
      document.body.addClass("rg-resizing");
      document.addEventListener("mousemove", onMove);
      document.addEventListener("mouseup", onUp);
    });
  });
  const tbody = table.createEl("tbody");
  for (const task of tasks) {
    renderRow(tbody, task, opts);
  }
}
function renderRow(tbody, task, opts) {
  const row = tbody.createEl("tr");
  row.style.height = `${rowHeightFor(opts.fontSize)}px`;
  if (task.isClosed)
    row.addClass("rg-row-closed");
  if (task.isContext)
    row.addClass("rg-row-context");
  row.addEventListener("contextmenu", (e) => {
    e.preventDefault();
    const menu = new import_obsidian5.Menu();
    menu.addItem(
      (item) => item.setTitle("\u30C1\u30B1\u30C3\u30C8\u5185\u5BB9\u3092\u30B3\u30D4\u30FC").setIcon("copy").onClick(async () => {
        const due = task.due && !task.dueIsFallback ? formatDate(task.due) : "-";
        const text = [
          `#${task.id}`,
          `${task.tracker} ${task.subject}`,
          `\u62C5\u5F53\u8005: ${task.assignee || "-"}`,
          `\u671F\u65E5: ${due}`,
          `\u7D0D\u671F: ${task.delivery || "-"}`,
          opts.issueUrl(task.id)
        ].join("\n");
        await navigator.clipboard.writeText(text);
        new import_obsidian5.Notice(`#${task.id} \u3092\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F`);
      })
    );
    menu.showAtMouseEvent(e);
  });
  const idCell = row.createEl("td", { cls: "rg-td-id" });
  idCell.createEl("a", {
    cls: "rg-issue-link",
    text: `#${task.id}`,
    href: opts.issueUrl(task.id)
  });
  const trackerCell = row.createEl("td");
  trackerCell.createSpan({ cls: "rg-tracker", text: task.tracker });
  const subjectCell = row.createEl("td", { cls: "rg-td-subject" });
  subjectCell.style.paddingLeft = `${10 + task.depth * INDENT2}px`;
  const link = subjectCell.createEl("a", {
    cls: "rg-issue-link",
    text: task.subject,
    href: opts.issueUrl(task.id)
  });
  link.setAttr("title", task.subject);
  const statusCell = row.createEl("td");
  statusCell.createSpan({
    cls: "rg-badge" + (task.isClosed ? " rg-badge-closed" : ""),
    text: task.status
  });
  const assigneeCell = row.createEl("td");
  if (task.assignee) {
    const chip = assigneeCell.createSpan({ cls: "rg-assignee-chip", text: task.assignee });
    const color = opts.assigneeColor(task.assignee);
    if (color) {
      chip.style.backgroundColor = color;
      chip.addClass("rg-assignee-chip-colored");
    }
  } else {
    assigneeCell.setText("-");
    assigneeCell.addClass("rg-td-empty");
  }
  const situationCell = row.createEl("td");
  const situation = computeSituation(task);
  if (situation) {
    const el = situationCell.createSpan({
      cls: `rg-due rg-due-${situation.kind}`,
      text: situation.text
    });
    if (situation.title)
      el.setAttr("title", situation.title);
  }
  row.createEl("td", {
    cls: "rg-td-date",
    text: task.start && !task.startIsFallback ? formatDate(task.start) : "-"
  });
  row.createEl("td", {
    cls: "rg-td-date",
    text: task.due && !task.dueIsFallback ? formatDate(task.due) : "-"
  });
  row.createEl("td", { cls: "rg-td-date", text: task.delivery || "-" });
  const ratioCell = row.createEl("td", { cls: "rg-td-ratio" });
  const ratioWrap = ratioCell.createDiv({ cls: "rg-ratio-wrap" });
  const bar = ratioWrap.createDiv({ cls: "rg-progress" });
  const fill = bar.createDiv({ cls: "rg-progress-fill" });
  fill.style.width = `${Math.min(task.doneRatio, 100)}%`;
  if (task.doneRatio >= 100)
    fill.addClass("rg-progress-done");
  ratioWrap.createSpan({ cls: "rg-progress-text", text: `${task.doneRatio}%` });
  const editCell = row.createEl("td", { cls: "rg-td-edit" });
  if (opts.onEdit) {
    const btn = editCell.createEl("button", { cls: "rg-edit-btn" });
    btn.style.height = "auto";
    btn.style.minHeight = "0";
    btn.style.lineHeight = "0";
    (0, import_obsidian5.setIcon)(btn, "pencil");
    btn.setAttr("aria-label", `#${task.id} \u3092\u7DE8\u96C6`);
    btn.addEventListener("click", () => opts.onEdit(task.id));
  }
}
function parseDeliveryDate(s) {
  const m = s.trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m)
    return null;
  return new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}
var DUE_SOON_DAYS = 14;
function situationInfo(task) {
  if (task.isClosed || task.isContext)
    return null;
  const due = task.due && !task.dueIsFallback ? task.due : null;
  const delivery = parseDeliveryDate(task.delivery);
  const label = due ? "\u671F\u65E5" : delivery ? "\u7D0D\u671F" : null;
  const target = due != null ? due : delivery;
  if (!label || !target)
    return null;
  const now = /* @__PURE__ */ new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  return { label, target, diff: diffDays(today, target) };
}
function matchesSituationFilter(task, filter) {
  const info = situationInfo(task);
  if (!info)
    return false;
  if (filter === "overdue")
    return info.diff < 0;
  if (filter === "week1")
    return info.diff >= 0 && info.diff <= 7;
  return info.diff >= 0 && info.diff <= 14;
}
function computeSituation(task) {
  const info = situationInfo(task);
  if (!info)
    return null;
  const { label, target, diff } = info;
  if (diff < 0) {
    return { text: `${label}\u8D85\u904E`, kind: "over", title: `${-diff}\u65E5\u8D85\u904E (${formatDate(target)})` };
  }
  if (diff > DUE_SOON_DAYS)
    return null;
  if (diff === 0) {
    return { text: `${label}\u672C\u65E5`, kind: "soon" };
  }
  return { text: `${label}\u3042\u3068${diff}\u65E5`, kind: "soon" };
}

// src/gantt/GanttView.ts
var VIEW_TYPE_REDMINE_GANTT = "redmine-gantt-view";
var ASSIGNEE_PALETTE = [
  "#3f7fd9",
  "#d94f70",
  "#3f9e4d",
  "#e8883a",
  "#7a5fd0",
  "#2f9e9b",
  "#b0578d",
  "#98771d"
];
var NO_ASSIGNEE = "";
var NO_ASSIGNEE_LABEL = "(\u62C5\u5F53\u8005\u306A\u3057)";
function parsePlanDate(s) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s))
    return null;
  const [y, m, d] = s.split("-").map(Number);
  return new Date(y, m - 1, d);
}
var GanttView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.rawIssues = null;
    this.statusEl = null;
    this.chartEl = null;
    this.scaleSelect = null;
    this.rangeControls = null;
    this.monthInput = null;
    this.assigneePanel = null;
    this.assigneeBtn = null;
    this.loading = false;
    this.lastFetchedAt = null;
    // 表示側のフィルタ状態(セッション内のみ保持)
    this.showClosed = false;
    this.selectedAssignees = /* @__PURE__ */ new Set();
    this.tableWidths = defaultTableWidths();
    this.ganttLeftWidth = DEFAULT_LEFT_WIDTH;
    // テーブル表示専用のフィルタ・分割状態(セッション内のみ保持)
    this.tableControls = null;
    this.tableSubjectFilter = "";
    this.tableSituationFilter = "all";
    this.tableGroupBy = "none";
    this.rangeMonths = 2;
    this.plugin = plugin;
    this.scale = plugin.settings.defaultScale;
    const now = /* @__PURE__ */ new Date();
    this.rangeYear = now.getFullYear();
    this.rangeMonth = now.getMonth();
  }
  getViewType() {
    return VIEW_TYPE_REDMINE_GANTT;
  }
  getDisplayText() {
    return "Redmine Gantt";
  }
  getIcon() {
    return "gantt-chart";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("rg-view");
    const toolbar = container.createDiv({ cls: "rg-toolbar" });
    const refreshBtn = toolbar.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian6.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.setAttr("aria-label", "\u518D\u53D6\u5F97");
    refreshBtn.addEventListener("click", () => void this.refresh());
    const modeSelect = toolbar.createEl("select", { cls: "dropdown rg-mode-select" });
    for (const [value, label] of [
      ["gantt", "\u30AC\u30F3\u30C8"],
      ["table", "\u30C6\u30FC\u30D6\u30EB"]
    ]) {
      const option = modeSelect.createEl("option", { text: label });
      option.value = value;
    }
    modeSelect.value = this.plugin.settings.viewMode;
    modeSelect.addEventListener("change", () => {
      this.plugin.settings.viewMode = modeSelect.value;
      void this.plugin.saveSettings();
      this.updateScaleVisibility();
      this.renderView();
    });
    const filterSelect = toolbar.createEl("select", { cls: "dropdown rg-filter-select" });
    const namedFilters = this.plugin.settings.filters.filter((f) => f.name);
    if (namedFilters.length === 0) {
      const option = filterSelect.createEl("option", { text: "(\u30D5\u30A3\u30EB\u30BF\u672A\u8A2D\u5B9A)" });
      option.value = "";
      filterSelect.disabled = true;
    } else {
      for (const filter of namedFilters) {
        const option = filterSelect.createEl("option", { text: filter.name });
        option.value = filter.name;
      }
      if (!this.activeFilter()) {
        this.plugin.settings.activeFilter = namedFilters[0].name;
        void this.plugin.saveSettings();
      }
      filterSelect.value = this.plugin.settings.activeFilter;
    }
    filterSelect.addEventListener("change", () => {
      this.plugin.settings.activeFilter = filterSelect.value;
      void this.plugin.saveSettings();
      this.selectedAssignees.clear();
      void this.refresh();
    });
    this.scaleSelect = toolbar.createEl("select", { cls: "dropdown rg-scale-select" });
    for (const [value, label] of [
      ["day", "\u65E5"],
      ["week", "\u9031"],
      ["month", "\u6708"]
    ]) {
      const option = this.scaleSelect.createEl("option", { text: label });
      option.value = value;
    }
    this.scaleSelect.value = this.scale;
    this.scaleSelect.addEventListener("change", () => {
      this.scale = this.scaleSelect.value;
      this.renderView();
    });
    this.rangeControls = toolbar.createDiv({ cls: "rg-range" });
    const prevBtn = this.rangeControls.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian6.setIcon)(prevBtn, "chevron-left");
    prevBtn.setAttr("aria-label", "\u524D\u6708\u3078");
    prevBtn.addEventListener("click", () => this.shiftRange(-1));
    this.monthInput = this.rangeControls.createEl("input", {
      cls: "rg-month-input",
      type: "month"
    });
    this.monthInput.value = this.monthInputValue();
    this.monthInput.addEventListener("change", () => {
      const m = this.monthInput.value.match(/^(\d{4})-(\d{2})$/);
      if (!m)
        return;
      this.rangeYear = Number(m[1]);
      this.rangeMonth = Number(m[2]) - 1;
      this.renderView();
    });
    const nextBtn = this.rangeControls.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian6.setIcon)(nextBtn, "chevron-right");
    nextBtn.setAttr("aria-label", "\u6B21\u6708\u3078");
    nextBtn.addEventListener("click", () => this.shiftRange(1));
    const monthsSelect = this.rangeControls.createEl("select", { cls: "dropdown" });
    for (const months of [1, 2, 3, 6, 12]) {
      const option = monthsSelect.createEl("option", { text: `${months}\u30F6\u6708` });
      option.value = String(months);
    }
    monthsSelect.value = String(this.rangeMonths);
    monthsSelect.addEventListener("change", () => {
      this.rangeMonths = Number(monthsSelect.value);
      this.renderView();
    });
    this.tableControls = toolbar.createDiv({ cls: "rg-table-controls" });
    const subjectInput = this.tableControls.createEl("input", {
      cls: "rg-subject-input",
      type: "search",
      placeholder: "\u984C\u540D\u3067\u7D5E\u308A\u8FBC\u307F"
    });
    subjectInput.value = this.tableSubjectFilter;
    subjectInput.addEventListener("input", () => {
      this.tableSubjectFilter = subjectInput.value;
      this.renderView();
    });
    const situationSelect = this.tableControls.createEl("select", { cls: "dropdown" });
    for (const [value, label] of [
      ["all", "\u72B6\u6CC1: \u3059\u3079\u3066"],
      ["week1", "1\u9031\u9593\u4EE5\u5185"],
      ["week2", "2\u9031\u9593\u4EE5\u5185"],
      ["overdue", "\u671F\u65E5\u30FB\u7D0D\u671F\u8D85\u904E"]
    ]) {
      const option = situationSelect.createEl("option", { text: label });
      option.value = value;
    }
    situationSelect.value = this.tableSituationFilter;
    situationSelect.addEventListener("change", () => {
      this.tableSituationFilter = situationSelect.value;
      this.renderView();
    });
    const groupSelect = this.tableControls.createEl("select", { cls: "dropdown" });
    for (const [value, label] of [
      ["none", "\u5206\u3051\u306A\u3044"],
      ["tracker", "\u30C8\u30E9\u30C3\u30AB\u30FC\u3067\u5206\u3051\u308B"],
      ["assignee", "\u62C5\u5F53\u8005\u3067\u5206\u3051\u308B"]
    ]) {
      const option = groupSelect.createEl("option", { text: label });
      option.value = value;
    }
    groupSelect.value = this.tableGroupBy;
    groupSelect.addEventListener("change", () => {
      this.tableGroupBy = groupSelect.value;
      this.renderView();
    });
    const closedLabel = toolbar.createEl("label", { cls: "rg-check" });
    const closedCheckbox = closedLabel.createEl("input", { type: "checkbox" });
    closedLabel.appendText("\u5B8C\u4E86");
    closedCheckbox.checked = this.showClosed;
    closedCheckbox.addEventListener("change", () => {
      this.showClosed = closedCheckbox.checked;
      this.renderView();
    });
    this.assigneeBtn = toolbar.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian6.setIcon)(this.assigneeBtn, "users");
    this.assigneeBtn.setAttr("aria-label", "\u62C5\u5F53\u8005\u3067\u7D5E\u308A\u8FBC\u307F");
    this.assigneeBtn.addEventListener("click", () => this.toggleAssigneePanel());
    const planBtn = toolbar.createEl("button", { cls: "rg-toolbar-btn" });
    (0, import_obsidian6.setIcon)(planBtn, "calendar-range");
    planBtn.setAttr("aria-label", "\u5168\u4F53\u4E88\u5B9A\u3092\u7DE8\u96C6");
    planBtn.addEventListener("click", () => {
      new PlanModal(this.app, this.plugin.settings.planItems, (items) => {
        this.plugin.settings.planItems = items;
        void this.plugin.saveSettings();
        this.renderView();
      }).open();
    });
    this.statusEl = toolbar.createDiv({ cls: "rg-status" });
    this.assigneePanel = toolbar.createDiv({ cls: "rg-assignee-panel" });
    this.assigneePanel.hide();
    this.registerDomEvent(document, "mousedown", (e) => {
      var _a;
      const target = e.target;
      if (this.assigneePanel && this.assigneePanel.isShown() && !this.assigneePanel.contains(target) && !((_a = this.assigneeBtn) == null ? void 0 : _a.contains(target))) {
        this.assigneePanel.hide();
      }
    });
    this.chartEl = container.createDiv({ cls: "rg-chart-container" });
    this.updateScaleVisibility();
    await this.refresh();
  }
  /** 選択中の表示フィルタ。未選択・無効なときは null */
  activeFilter() {
    var _a;
    const name = this.plugin.settings.activeFilter;
    if (!name)
      return null;
    return (_a = this.plugin.settings.filters.find((f) => f.name === name)) != null ? _a : null;
  }
  updateScaleVisibility() {
    const isTable = this.plugin.settings.viewMode === "table";
    const ganttDisplay = isTable ? "none" : "";
    if (this.scaleSelect)
      this.scaleSelect.style.display = ganttDisplay;
    if (this.rangeControls)
      this.rangeControls.style.display = ganttDisplay;
    if (this.tableControls)
      this.tableControls.style.display = isTable ? "" : "none";
  }
  monthInputValue() {
    return `${this.rangeYear}-${String(this.rangeMonth + 1).padStart(2, "0")}`;
  }
  shiftRange(deltaMonths) {
    const d = new Date(this.rangeYear, this.rangeMonth + deltaMonths, 1);
    this.rangeYear = d.getFullYear();
    this.rangeMonth = d.getMonth();
    if (this.monthInput)
      this.monthInput.value = this.monthInputValue();
    this.renderView();
  }
  ganttRange() {
    return monthRange(this.rangeYear, this.rangeMonth, this.rangeMonths);
  }
  async refresh() {
    if (this.loading || !this.chartEl)
      return;
    const filter = this.activeFilter();
    if (!filter) {
      this.rawIssues = null;
      this.setStatus("\u30D5\u30A3\u30EB\u30BF\u672A\u8A2D\u5B9A");
      this.chartEl.empty();
      this.chartEl.createDiv({
        cls: "rg-empty",
        text: "\u8868\u793A\u30D5\u30A3\u30EB\u30BF\u304C\u8A2D\u5B9A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\n\u8A2D\u5B9A \u2192 Redmine Gantt \u2192 \u300C\u8868\u793A\u30D5\u30A3\u30EB\u30BF\u300D\u3067\u3001\u89AA\u30C1\u30B1\u30C3\u30C8\u914D\u4E0B\u307E\u305F\u306F\u4FDD\u5B58\u30AF\u30A8\u30EA\u306E\u30D5\u30A3\u30EB\u30BF\u3092\u8FFD\u52A0\u3057\u3066\u304F\u3060\u3055\u3044\u3002\n(\u8CA0\u8377\u3092\u6291\u3048\u308B\u305F\u3081\u3001\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u5168\u4F53\u306E\u4E00\u62EC\u53D6\u5F97\u306F\u884C\u3044\u307E\u305B\u3093)"
      });
      return;
    }
    this.loading = true;
    this.setStatus("\u53D6\u5F97\u4E2D\u2026");
    try {
      const client = new RedmineClient(this.plugin.settings);
      this.rawIssues = await client.fetchIssues(filter);
      const now = /* @__PURE__ */ new Date();
      const hh = String(now.getHours()).padStart(2, "0");
      const mm = String(now.getMinutes()).padStart(2, "0");
      this.lastFetchedAt = `${hh}:${mm}`;
      this.renderView();
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      this.setStatus("\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
      this.chartEl.empty();
      this.chartEl.createDiv({ cls: "rg-error", text: message });
      new import_obsidian6.Notice(`Redmine Gantt: ${message}`);
    } finally {
      this.loading = false;
    }
  }
  /**
   * 表示側フィルタ(完了・担当者)を適用したチケット群。
   * 絞り込みで非表示になった親は「コンテキスト」として補い、ツリー構造を維持する。
   */
  visibleIssues() {
    var _a, _b, _c, _d;
    if (!this.rawIssues)
      return { issues: [], contextIds: /* @__PURE__ */ new Set() };
    const filter = this.activeFilter();
    const rootId = (filter == null ? void 0 : filter.type) === "parent" ? Number(filter.value.trim()) : NaN;
    const visible = /* @__PURE__ */ new Set();
    for (const issue of this.rawIssues) {
      if (issue.id !== rootId) {
        if (!this.showClosed && issue.closed_on)
          continue;
        if (this.selectedAssignees.size > 0 && !this.selectedAssignees.has((_b = (_a = issue.assigned_to) == null ? void 0 : _a.name) != null ? _b : NO_ASSIGNEE)) {
          continue;
        }
      }
      visible.add(issue.id);
    }
    const byId = new Map(this.rawIssues.map((issue) => [issue.id, issue]));
    const contextIds = /* @__PURE__ */ new Set();
    for (const issue of this.rawIssues) {
      if (!visible.has(issue.id))
        continue;
      let parentId = (_c = issue.parent) == null ? void 0 : _c.id;
      while (parentId !== void 0 && !visible.has(parentId) && !contextIds.has(parentId)) {
        const parent = byId.get(parentId);
        if (!parent)
          break;
        contextIds.add(parent.id);
        parentId = (_d = parent.parent) == null ? void 0 : _d.id;
      }
    }
    return {
      issues: this.rawIssues.filter(
        (issue) => visible.has(issue.id) || contextIds.has(issue.id)
      ),
      contextIds
    };
  }
  /**
   * 担当者→表示色。
   * 設定の固定色が最優先(フィルタや絞り込みの選択にかかわらず常に適用)。
   * 次に担当者絞り込みモードの自動配色。どちらも該当しなければ null
   */
  assigneeColor(assignee) {
    const fixed = this.plugin.settings.assigneeColors.find(
      (entry) => entry.name !== "" && entry.name === assignee
    );
    if (fixed)
      return fixed.color;
    if (this.selectedAssignees.size === 0)
      return null;
    const sorted = Array.from(this.selectedAssignees).sort();
    const index = sorted.indexOf(assignee);
    if (index < 0)
      return null;
    return ASSIGNEE_PALETTE[index % ASSIGNEE_PALETTE.length];
  }
  toggleAssigneePanel() {
    if (!this.assigneePanel || !this.assigneeBtn)
      return;
    if (this.assigneePanel.isShown()) {
      this.assigneePanel.hide();
      return;
    }
    this.renderAssigneePanel();
    this.assigneePanel.style.left = `${this.assigneeBtn.offsetLeft}px`;
    this.assigneePanel.show();
  }
  renderAssigneePanel() {
    var _a, _b, _c;
    const panel = this.assigneePanel;
    if (!panel)
      return;
    panel.empty();
    panel.createDiv({ cls: "rg-assignee-panel-title", text: "\u62C5\u5F53\u8005\u3067\u7D5E\u308A\u8FBC\u307F" });
    if (!this.rawIssues || this.rawIssues.length === 0) {
      panel.createDiv({ cls: "rg-assignee-empty", text: "\u30C1\u30B1\u30C3\u30C8\u304C\u3042\u308A\u307E\u305B\u3093" });
      return;
    }
    const counts = /* @__PURE__ */ new Map();
    for (const issue of this.rawIssues) {
      const name = (_b = (_a = issue.assigned_to) == null ? void 0 : _a.name) != null ? _b : NO_ASSIGNEE;
      counts.set(name, ((_c = counts.get(name)) != null ? _c : 0) + 1);
    }
    const names = Array.from(counts.keys()).sort((a, b) => {
      if (a === NO_ASSIGNEE)
        return 1;
      if (b === NO_ASSIGNEE)
        return -1;
      return a.localeCompare(b, "ja");
    });
    for (const name of names) {
      const item = panel.createEl("label", { cls: "rg-assignee-item" });
      const checkbox = item.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedAssignees.has(name);
      const dot = item.createSpan({ cls: "rg-assignee-dot" });
      const color = this.assigneeColor(name);
      if (color)
        dot.style.backgroundColor = color;
      item.createSpan({ text: name === NO_ASSIGNEE ? NO_ASSIGNEE_LABEL : name });
      item.createSpan({ cls: "rg-assignee-count", text: String(counts.get(name)) });
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedAssignees.add(name);
        } else {
          this.selectedAssignees.delete(name);
        }
        this.renderAssigneePanel();
        this.renderView();
      });
    }
    const footer = panel.createDiv({ cls: "rg-assignee-footer" });
    const clearBtn = footer.createEl("button", { text: "\u9078\u629E\u89E3\u9664" });
    clearBtn.disabled = this.selectedAssignees.size === 0;
    clearBtn.addEventListener("click", () => {
      this.selectedAssignees.clear();
      this.renderAssigneePanel();
      this.renderView();
    });
  }
  /** 全体予定を表示用に変換する(開始日順、日付なしは末尾) */
  planRows() {
    const rows = this.plugin.settings.planItems.map((item) => {
      let start = parsePlanDate(item.start);
      let end = parsePlanDate(item.end);
      if (start && end && start > end)
        [start, end] = [end, start];
      if (start && !end)
        end = start;
      if (!start && end)
        start = end;
      return { name: item.name, start, end, status: item.status };
    });
    return rows.sort((a, b) => {
      if (!a.start)
        return 1;
      if (!b.start)
        return -1;
      return a.start.getTime() - b.start.getTime();
    });
  }
  /** 設定変更などによる外部からの再描画 */
  rerender() {
    this.renderView();
  }
  /** 表示側フィルタを適用して再描画する(再取得はしない) */
  renderView() {
    if (!this.chartEl || !this.rawIssues)
      return;
    const { issues, contextIds } = this.visibleIssues();
    const model = buildGanttModel(issues, contextIds);
    const client = new RedmineClient(this.plugin.settings);
    const opts = {
      issueUrl: (id) => client.issueUrl(id),
      assigneeColor: (assignee) => this.assigneeColor(assignee),
      fontSize: this.plugin.settings.tableFontSize,
      leftWidth: this.ganttLeftWidth,
      onLeftWidthChange: (width) => {
        this.ganttLeftWidth = width;
      }
    };
    if (this.plugin.settings.viewMode === "table") {
      renderTable(this.chartEl, model, {
        ...opts,
        widths: this.tableWidths,
        onEdit: (issueId) => this.openEditModal(issueId),
        subjectFilter: this.tableSubjectFilter,
        situationFilter: this.tableSituationFilter,
        groupBy: this.tableGroupBy
      });
    } else {
      renderGantt(this.chartEl, model, this.planRows(), this.scale, this.ganttRange(), opts);
    }
    const suffix = this.lastFetchedAt ? ` / \u6700\u7D42\u66F4\u65B0 ${this.lastFetchedAt}` : "";
    const shown = issues.length - contextIds.size;
    this.setStatus(`\u8868\u793A ${shown} / \u53D6\u5F97 ${this.rawIssues.length}\u4EF6${suffix}`);
  }
  /** チケット編集モーダルを開き、保存後は該当チケットだけ差し替えて再描画する */
  openEditModal(issueId) {
    const client = new RedmineClient(this.plugin.settings);
    new IssueEditModal(this.app, client, issueId, (updated) => {
      if (this.rawIssues) {
        const index = this.rawIssues.findIndex((issue) => issue.id === updated.id);
        if (index >= 0) {
          this.rawIssues[index] = updated;
        }
      }
      this.renderView();
    }).open();
  }
  setStatus(text) {
    var _a;
    (_a = this.statusEl) == null ? void 0 : _a.setText(text);
  }
  async onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var RedmineGanttPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_REDMINE_GANTT, (leaf) => new GanttView(leaf, this));
    this.addRibbonIcon("gantt-chart", "Redmine Gantt \u3092\u958B\u304F", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-gantt-view",
      name: "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u3092\u958B\u304F",
      callback: () => void this.activateView()
    });
    this.addSettingTab(new RedmineGanttSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_REDMINE_GANTT);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_REDMINE_GANTT, active: true });
    }
    await workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings.filters = this.settings.filters.filter(
      (f) => f.type === "parent" || f.type === "query"
    );
    if (this.settings.activeFilter && !this.settings.filters.some((f) => f.name === this.settings.activeFilter)) {
      this.settings.activeFilter = "";
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** 開いているガントビューを再描画する(設定変更の即時反映用) */
  refreshGanttViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_REDMINE_GANTT)) {
      const view = leaf.view;
      if (view instanceof GanttView) {
        view.rerender();
      }
    }
  }
};
